name: dev

on:
  push:
    branches:
      - 'mausam/actor-proxy-timeouts'
    paths-ignore:
      - "scripts/**"
      - "tools/**"
      - "jenkins/**"
      - "notes/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v3

      - name: Install CS native
        run: |
          curl -fLo cs https://git.io/coursier-cli-linux
          chmod +x cs
          sudo mv cs /usr/local/bin
          cs install --add-channel https://raw.githubusercontent.com/tmtsoftware/osw-apps/master/apps.json

      - name: Tests
        run: sbt -Dakka.actor.serialize-messages=on test:test
